[tool.bandit]
skips = ["B101", "B311", "B308"]

[tool.mypy]
python_version = "3.13"
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
warn_return_any = true
#ignore_missing_imports = true
